repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.8
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix ]
      exclude: |
        ^hgcn/ |
        ^layers/
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
      exclude: |
        ^hgcn/ |
        ^layers/
